apiVersion: v1
kind: ServiceAccount
metadata:
  name: dolt-operator
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: dolt-operator
  namespace: default
  annotations:
    kubernetes.io/service-account.name: dolt-operator
type: kubernetes.io/service-account-token