apiVersion: k8s.dolthub.com/v1alpha
kind: Database
metadata:
  name: database-sample
spec:
  name: dbsample
  doltDBRef:
    name: dolt
    namespace: default
  systemBranches:
    - master
    - global
  doltIgnorePatterns: []

