apiVersion: v1
kind: Service
metadata:
  name: doltdb-0-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.10
spec:
  ports:
  - name: doltdb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: doltdb
    app.kubernetes.io/name: doltdb
    statefulset.kubernetes.io/pod-name: doltdb-0  
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: doltdb-1-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.11
spec:
  ports:
  - name: doltdb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: doltdb
    app.kubernetes.io/name: doltdb
    statefulset.kubernetes.io/pod-name: doltdb-1 
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: doltdb-2-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.12
spec:
  ports:
  - name: doltdb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: doltdb
    app.kubernetes.io/name: doltdb
    statefulset.kubernetes.io/pod-name: doltdb-2
  type: LoadBalancer
