apiVersion: k8s.dolthub.com/v1alpha
kind: User
metadata:
  name: sample-user
spec:
  name: "sample-user"
  host: "%"
  passwordSecretKeyRef: 
    name: "doltdb-sample-user" # Name of the secret present in the namespace
    key: "password" # Key in the secret that contains the password
  doltDBRef:
   name: dolt
   namespace: default